# Generated by Django 2.2 on 2019-08-12 13:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='date_updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 8, 12, 18, 37, 59, 378712)),
        ),
        migrations.AlterField(
            model_name='field',
            name='date_updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 8, 12, 18, 37, 59, 377715)),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='date_updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 8, 12, 18, 37, 59, 383697)),
        ),
        migrations.AlterField(
            model_name='product',
            name='date_updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 8, 12, 18, 37, 59, 382699)),
        ),
        migrations.AlterField(
            model_name='resultfields',
            name='date_updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 8, 12, 18, 37, 59, 381702)),
        ),
        migrations.AlterField(
            model_name='sample',
            name='date_updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 8, 12, 18, 37, 59, 379710)),
        ),
        migrations.AlterField(
            model_name='sampletest',
            name='date_updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 8, 12, 18, 37, 59, 380705)),
        ),
        migrations.AlterField(
            model_name='sampleteststatus',
            name='date_updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 8, 12, 18, 37, 59, 382699)),
        ),
        migrations.AlterField(
            model_name='section',
            name='date_updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 8, 12, 18, 37, 59, 375719)),
        ),
        migrations.AlterField(
            model_name='test',
            name='date_updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 8, 12, 18, 37, 59, 376718)),
        ),
    ]
