# Generated by Django 2.2 on 2019-08-12 13:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0002_auto_20190812_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='date_updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 8, 12, 19, 12, 58, 840627)),
        ),
        migrations.AlterField(
            model_name='field',
            name='date_updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 8, 12, 19, 12, 58, 840627)),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='date_updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 8, 12, 19, 12, 58, 846610)),
        ),
        migrations.AlterField(
            model_name='product',
            name='date_updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 8, 12, 19, 12, 58, 845613)),
        ),
        migrations.AlterField(
            model_name='resultfields',
            name='date_updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 8, 12, 19, 12, 58, 843618)),
        ),
        migrations.AlterField(
            model_name='sample',
            name='date_updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 8, 12, 19, 12, 58, 841623)),
        ),
        migrations.AlterField(
            model_name='sampletest',
            name='date_updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 8, 12, 19, 12, 58, 842620)),
        ),
        migrations.AlterField(
            model_name='sampleteststatus',
            name='date_updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 8, 12, 19, 12, 58, 844615)),
        ),
        migrations.AlterField(
            model_name='sampleteststatus',
            name='sampletest',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='sampleteststatussampletest', to='lims.SampleTest'),
        ),
        migrations.AlterField(
            model_name='section',
            name='date_updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 8, 12, 19, 12, 58, 838632)),
        ),
        migrations.AlterField(
            model_name='test',
            name='date_updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 8, 12, 19, 12, 58, 839629)),
        ),
    ]
