# Generated by Django 2.2 on 2019-08-13 17:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0006_auto_20190813_2255'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='created_by',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='updated_by',
            new_name='updated',
        ),
        migrations.RenameField(
            model_name='field',
            old_name='created_by',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='field',
            old_name='updated_by',
            new_name='updated',
        ),
        migrations.RenameField(
            model_name='sample',
            old_name='created_by',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='sample',
            old_name='updated_by',
            new_name='updated',
        ),
        migrations.RenameField(
            model_name='sampletest',
            old_name='created_by',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='sampletest',
            old_name='updated_by',
            new_name='updated',
        ),
        migrations.RenameField(
            model_name='section',
            old_name='created_by',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='section',
            old_name='updated_by',
            new_name='updated',
        ),
        migrations.RenameField(
            model_name='test',
            old_name='created_by',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='test',
            old_name='updated_by',
            new_name='updated',
        ),
        migrations.AlterField(
            model_name='client',
            name='date_updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 8, 13, 23, 4, 48, 8451)),
        ),
        migrations.AlterField(
            model_name='field',
            name='date_updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 8, 13, 23, 4, 48, 8451)),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='date_updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 8, 13, 23, 4, 48, 13437)),
        ),
        migrations.AlterField(
            model_name='product',
            name='date_updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 8, 13, 23, 4, 48, 12439)),
        ),
        migrations.AlterField(
            model_name='resultfields',
            name='date_updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 8, 13, 23, 4, 48, 11406)),
        ),
        migrations.AlterField(
            model_name='sample',
            name='date_updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 8, 13, 23, 4, 48, 9446)),
        ),
        migrations.AlterField(
            model_name='sampletest',
            name='date_updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 8, 13, 23, 4, 48, 11406)),
        ),
        migrations.AlterField(
            model_name='section',
            name='date_updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 8, 13, 23, 4, 48, 6418)),
        ),
        migrations.AlterField(
            model_name='test',
            name='date_updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 8, 13, 23, 4, 48, 7457)),
        ),
    ]
