# Generated by Django 2.2 on 2019-08-12 13:43

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lims', '0004_auto_20190812_1913'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(max_length=50)),
                ('date_updated', models.DateTimeField(blank=True, default=datetime.datetime(2019, 8, 12, 19, 13, 29, 481425))),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Module_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Module_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, null=True)),
                ('phone', models.CharField(default='', max_length=20, null=True)),
                ('address', models.CharField(blank=True, max_length=150, null=True)),
                ('status', models.CharField(blank=True, max_length=10, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='profile/')),
                ('date_updated', models.DateTimeField(blank=True, default=datetime.datetime(2019, 8, 12, 19, 13, 29, 479427))),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=50)),
                ('date_updated', models.DateTimeField(blank=True, default=datetime.datetime(2019, 8, 12, 19, 13, 29, 482418))),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Role_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Role_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Scope',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_set', models.TextField(blank=True, null=True)),
                ('date_updated', models.DateTimeField(blank=True, default=datetime.datetime(2019, 8, 12, 19, 13, 29, 483414))),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Scope_created_by', to=settings.AUTH_USER_MODEL)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scope_Module', to='users.Module')),
                ('scope_module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scope_scopemodule', to='users.Module')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Scope_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create', models.BooleanField(default=False)),
                ('read', models.BooleanField(default=True)),
                ('update', models.BooleanField(default=False)),
                ('delete', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[('FullAccess', 'FullAccess'), ('ReadOnly', 'ReadOnly'), ('OnlyOwner', 'OnlyOwner'), ('OnlyCreated', 'OnlyCreated'), ('OnlySuperAdmin', 'OnlySuperAdmin')], default='FullAccess', max_length=50)),
                ('date_updated', models.DateTimeField(blank=True, default=datetime.datetime(2019, 8, 12, 19, 13, 29, 484413))),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='RolePersission_created_by', to=settings.AUTH_USER_MODEL)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rolepermission_module', to='users.Module')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rolepermission_role', to='users.Role')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='RolePersission_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_updated', models.DateTimeField(blank=True, default=datetime.datetime(2019, 8, 12, 19, 13, 29, 485410))),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ProfileRole_created_by', to=settings.AUTH_USER_MODEL)),
                ('depertment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profilerole_depertment', to='lims.Section')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profilerole_role', to='users.Role')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ProfileRole_updated_by', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profilerole_profile', to='users.Profile')),
            ],
        ),
    ]
