# Generated by Django 2.2 on 2019-08-13 12:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='date_updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 8, 13, 18, 26, 44, 544589)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='date_updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 8, 13, 18, 26, 44, 543551)),
        ),
        migrations.AlterField(
            model_name='profilerole',
            name='date_updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 8, 13, 18, 26, 44, 546582)),
        ),
        migrations.AlterField(
            model_name='role',
            name='date_updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 8, 13, 18, 26, 44, 544589)),
        ),
        migrations.AlterField(
            model_name='rolepermission',
            name='date_updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 8, 13, 18, 26, 44, 546582)),
        ),
        migrations.AlterField(
            model_name='scope',
            name='date_updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 8, 13, 18, 26, 44, 545589)),
        ),
    ]
