# Generated by Django 2.2 on 2019-08-13 17:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190813_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='date_updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 8, 13, 22, 55, 48, 331898)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='date_updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 8, 13, 22, 55, 48, 330866)),
        ),
        migrations.AlterField(
            model_name='profilerole',
            name='date_updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 8, 13, 22, 55, 48, 334896)),
        ),
        migrations.AlterField(
            model_name='role',
            name='date_updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 8, 13, 22, 55, 48, 332899)),
        ),
        migrations.AlterField(
            model_name='rolepermission',
            name='date_updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 8, 13, 22, 55, 48, 333895)),
        ),
        migrations.AlterField(
            model_name='scope',
            name='date_updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 8, 13, 22, 55, 48, 332899)),
        ),
    ]
