# Generated by Django 2.2 on 2019-08-13 17:35

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0003_auto_20190813_2255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='module',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='profilerole',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='profilerole',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='role',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='role',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='rolepermission',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='rolepermission',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='scope',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='scope',
            name='updated_by',
        ),
        migrations.AddField(
            model_name='module',
            name='created',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Module_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='module',
            name='updated',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Module_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profilerole',
            name='created',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ProfileRole_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profilerole',
            name='updated',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ProfileRole_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='role',
            name='created',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Role_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='role',
            name='updated',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Role_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rolepermission',
            name='created',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='RolePersission_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rolepermission',
            name='updated',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='RolePersission_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scope',
            name='created',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Scope_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scope',
            name='updated',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Scope_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='module',
            name='date_updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 8, 13, 23, 4, 48, 124140)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='date_updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 8, 13, 23, 4, 48, 123106)),
        ),
        migrations.AlterField(
            model_name='profilerole',
            name='date_updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 8, 13, 23, 4, 48, 127136)),
        ),
        migrations.AlterField(
            model_name='role',
            name='date_updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 8, 13, 23, 4, 48, 124140)),
        ),
        migrations.AlterField(
            model_name='rolepermission',
            name='date_updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 8, 13, 23, 4, 48, 126137)),
        ),
        migrations.AlterField(
            model_name='scope',
            name='date_updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 8, 13, 23, 4, 48, 125140)),
        ),
    ]
